spring:
  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

# 운영환경에서 sql 로그가 비활성화 된 이유는 보안/성능상 리스크 때문
# sql 로그에 사용자 정보가 포함될 수도 있고 다량의 로그는 성능저하를 유발함
# 운영환경 로그 필요시 로그 레벨로 출력하거나 로깅 프레임워크와 연동해서 sql 로그를 파일로 분리하는 것이 추천됨
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true